name: Build 6.0 server library

on: [push, pull_request]

jobs:
  build-6-0-server:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - run: msbuild server/sdev.sln /p:configuration=release /p:platform="x86" /p:ShaiyaEpisode=6
      - uses: actions/upload-artifact@v1
        with:
          name: sdev.dll
          path: server/release/sdev.dll
      - uses: actions/upload-artifact@v1
        with:
          name: sdev.pdb
          path: server/release/sdev.pdb